/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import domain.Rectangle;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;

/**
 *
 * @author Caro
 */
public class PlayWindow extends JFrame {

    /**
     * Creates new form PlayWindow
     */
    
    
    private Font font, fontDos;
      private int speed;
    private int quantity;
    private Rectangle mySquare;
    
    public PlayWindow(Rectangle mySquare, int quantity, int speed) {
        initComponents();
         this.setTitle("Speedway");
        ((JPanel)getContentPane()).setOpaque(false);
            ImageIcon uno = new ImageIcon(this.getClass().getResource("/assets/pista5.jpg"));
            JLabel fondo = new JLabel();
            fondo.setIcon(uno);
            getLayeredPane().add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);
            fondo.setBounds(0, 0, uno.getIconWidth(), uno.getIconHeight());
        this.font = new Font("Century gothic", Font.BOLD, 14);
        this.fontDos = new Font("Century gothic", Font.BOLD, 15);
        
        this.speed=speed;
        this.quantity=quantity;
        this.mySquare=mySquare;
        
    }
    
      @Override
    public void paint(Graphics g){
        super.paint(g);
        int amount=0;
        
        //iterate over all squares
        for (int i = 0; i < quantity; i++) {
            int randomColor=(int)(Math.random()*4)+1;
            int carril=50;
            switch(randomColor){
                case 1:
                    carril=50;
                    break;
                case 2:
                    carril=115;
                    break;
                case 3:
                    carril=180;
                    break;
                case 4:
                    carril=50;
                    break;
            }
            switch(speed){
                case 250:
                    g.setColor (Color.blue);
                    mySquare.setyAxis(amount);
                    g.drawString(mySquare.getIdentification(),mySquare.getxAxis(),mySquare.getyAxis()+amount-5);
                    g.fillRect(mySquare.getxAxis(), mySquare.getyAxis(), mySquare.getWidth(), mySquare.getHeight());
                    break;
                case 450:
                    g.setColor (Color.cyan);
                    mySquare.setyAxis(amount);
                    g.drawString(mySquare.getIdentification(),mySquare.getxAxis(),mySquare.getyAxis()+amount-5);
                    g.fillRect(mySquare.getxAxis(), mySquare.getyAxis(), mySquare.getWidth(), mySquare.getHeight());
                    break;
                case 600:
                    g.setColor (Color.black);
                    mySquare.setyAxis(amount);
                    g.drawString(mySquare.getIdentification(),mySquare.getxAxis(),mySquare.getyAxis()+amount-5);
                    g.fillRect(mySquare.getxAxis(), mySquare.getyAxis(), mySquare.getWidth(), mySquare.getHeight());
                    break;
                case 800:
                    g.setColor (Color.gray);
                    mySquare.setyAxis(amount);
                    g.drawString(mySquare.getIdentification(),mySquare.getxAxis(),mySquare.getyAxis()+amount-5);
                    g.fillRect(mySquare.getxAxis(), mySquare.getyAxis(), mySquare.getWidth(), mySquare.getHeight());
                    break;
            }
            if (amount>=420) {
                amount=0;
                
            } else {
                amount+=70;
            }
        } //end for
    }
    
    public void paintAgain(){
        repaint();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jtValue = new javax.swing.JTextField();
        jlSpeed = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jbBarrier = new javax.swing.JButton();
        jbInterrupt = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jbRevert = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        comboImage = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/create.png"))); // NOI18N
        jButton1.setBorder(null);

        jtValue.setBackground(new java.awt.Color(0, 204, 0));
        jtValue.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jtValue.setForeground(new java.awt.Color(255, 255, 255));
        jtValue.setText("Value");
        jtValue.setBorder(null);

        jlSpeed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/speed.jpg"))); // NOI18N

        jComboBox1.setBackground(new java.awt.Color(0, 204, 51));
        jComboBox1.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High Speed", "Middle Speed", "Middle Low Speed", "Low Speed" }));
        jComboBox1.setBorder(null);

        jbBarrier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/barrier1.jpg"))); // NOI18N
        jbBarrier.setBorder(null);
        jbBarrier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBarrierActionPerformed(evt);
            }
        });

        jbInterrupt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/interrupt1.jpg"))); // NOI18N
        jbInterrupt.setActionCommand("");
        jbInterrupt.setBorder(null);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/simulation1.jpg"))); // NOI18N
        jButton2.setBorder(null);

        jbRevert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/revert1.jpg"))); // NOI18N
        jbRevert.setBorder(null);

        jTextField1.setBackground(new java.awt.Color(0, 204, 51));
        jTextField1.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(null);

        comboImage.setBackground(new java.awt.Color(0, 204, 51));
        comboImage.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        comboImage.setForeground(new java.awt.Color(255, 255, 255));
        comboImage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Shape", "Image" }));
        comboImage.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, 0, 1, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbBarrier)
                        .addGap(28, 28, 28)
                        .addComponent(jbRevert)
                        .addGap(18, 18, 18)
                        .addComponent(jbInterrupt)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(comboImage, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(535, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jTextField1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addComponent(jButton2))
                    .addComponent(jlSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBarrier)
                    .addComponent(jbRevert)
                    .addComponent(jbInterrupt)
                    .addComponent(comboImage, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBarrierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBarrierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbBarrierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PlayWindow().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboImage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbBarrier;
    private javax.swing.JButton jbInterrupt;
    private javax.swing.JButton jbRevert;
    private javax.swing.JLabel jlSpeed;
    private javax.swing.JTextField jtValue;
    // End of variables declaration//GEN-END:variables
}
